### ISSUE TITLE
Error message on Kodi 19.3

### ISSUE THREAD

**Issue by Mystery86HH** [andrew-ld/smart-tv-telegram#22]
Hello, i send a video to the bot, than I choose my device inside of telegram. Then I got in Kodi the message (I try to translate from German to English): "Playback not possible: General error during playback.  See log for more information."

The I click ok on that message and click on play inside the telegram bot and the video starts to play correctly.

The log from the bot:
      

2022-02-19T13:56:51.139356210Z ERROR:aiohttp.server:Error handling request

2022-02-19T13:56:51.139859422Z Traceback (most recent call last):

2022-02-19T13:56:51.139898404Z   File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request

2022-02-19T13:56:51.139943449Z     resp = await request_handler(request)

2022-02-19T13:56:51.139973970Z   File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle

2022-02-19T13:56:51.140007634Z     resp = await handler(request)

2022-02-19T13:56:51.140034669Z   File "/usr/local/lib/python3.10/site-packages/smart_tv_telegram/http.py", line 199, in _stream_handler

2022-02-19T13:56:51.140071826Z     message = await self._mtproto.get_message(int(message_id))

2022-02-19T13:56:51.140102307Z   File "/usr/local/lib/python3.10/site-packages/async_lru.py", line 237, in wrapped

2022-02-19T13:56:51.140159258Z     return (yield from asyncio.shield(fut, loop=_loop))

2022-02-19T13:56:51.140193645Z TypeError: shield() got an unexpected keyword argument 'loop'

2022-02-19T13:56:51.155174446Z ERROR:aiohttp.server:Error handling request

2022-02-19T13:56:51.155308508Z Traceback (most recent call last):

2022-02-19T13:56:51.155340919Z   File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request

2022-02-19T13:56:51.155380615Z     resp = await request_handler(request)

2022-02-19T13:56:51.155408669Z   File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle

2022-02-19T13:56:51.155439415Z     resp = await handler(request)

2022-02-19T13:56:51.155467352Z   File "/usr/local/lib/python3.10/site-packages/smart_tv_telegram/http.py", line 199, in _stream_handler

2022-02-19T13:56:51.155498567Z     message = await self._mtproto.get_message(int(message_id))

2022-02-19T13:56:51.155526554Z   File "/usr/local/lib/python3.10/site-packages/async_lru.py", line 212, in wrapped

2022-02-19T13:56:51.155563856Z     return (yield from asyncio.shield(fut, loop=_loop))

2022-02-19T13:56:51.155591498Z TypeError: shield() got an unexpected keyword argument 'loop'

2022-02-19T13:56:51.176612909Z ERROR:aiohttp.server:Error handling request

2022-02-19T13:56:51.176726014Z Traceback (most recent call last):

2022-02-19T13:56:51.176771796Z   File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request

2022-02-19T13:56:51.176810056Z     resp = await request_handler(request)

2022-02-19T13:56:51.176837468Z   File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle

2022-02-19T13:56:51.176868097Z     resp = await handler(request)

2022-02-19T13:56:51.176893363Z   File "/usr/local/lib/python3.10/site-packages/smart_tv_telegram/http.py", line 199, in _stream_handler

2022-02-19T13:56:51.176924518Z     message = await self._mtproto.get_message(int(message_id))

2022-02-19T13:56:51.176952683Z   File "/usr/local/lib/python3.10/site-packages/async_lru.py", line 212, in wrapped

2022-02-19T13:56:51.176981317Z     return (yield from asyncio.shield(fut, loop=_loop))

2022-02-19T13:56:51.177008257Z TypeError: shield() got an unexpected keyword argument 'loop'

2022-02-19T13:56:51.196970907Z ERROR:aiohttp.server:Error handling request

2022-02-19T13:56:51.197108377Z Traceback (most recent call last):

2022-02-19T13:56:51.197143613Z   File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request

2022-02-19T13:56:51.197186016Z     resp = await request_handler(request)

2022-02-19T13:56:51.197213981Z   File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle

2022-02-19T13:56:51.197245273Z     resp = await handler(request)

2022-02-19T13:56:51.197271746Z   File "/usr/local/lib/python3.10/site-packages/smart_tv_telegram/http.py", line 199, in _stream_handler

2022-02-19T13:56:51.197302690Z     message = await self._mtproto.get_message(int(message_id))

2022-02-19T13:56:51.197331778Z   File "/usr/local/lib/python3.10/site-packages/async_lru.py", line 212, in wrapped

2022-02-19T13:56:51.197364021Z     return (yield from asyncio.shield(fut, loop=_loop))

2022-02-19T13:56:51.197391282Z TypeError: shield() got an unexpected keyword argument 'loop'
`

**Comment by Mystery86HH** [comment]
This is from Kodi log:

2022-02-19 15:26:26.742 T:9609     INFO <general>: VideoPlayer::OpenFile: http://192.168.178.145:8350/stream/2200/13183260614721610628
2022-02-19 15:26:26.775 T:9609    ERROR <general>: CCurlFile::Stat - Failed: HTTP response code said error(22) for http://192.168.178.145:8350/stream/2200/13183260614721610628
2022-02-19 15:26:26.780 T:10082    INFO <general>: Creating InputStream
2022-02-19 15:26:26.795 T:10082   ERROR <general>: CCurlFile::FillBuffer - Failed: HTTP returned error 500
2022-02-19 15:26:26.796 T:10082   ERROR <general>: CCurlFile::Open failed with code 500 for http://192.168.178.145:8350/stream/2200/13183260614721610628:
                                                   
2022-02-19 15:26:26.805 T:10082   ERROR <general>: CCurlFile::FillBuffer - Failed: HTTP returned error 500
2022-02-19 15:26:26.806 T:10082   ERROR <general>: CCurlFile::Open failed with code 500 for http://192.168.178.145:8350/stream/2200/13183260614721610628:
                                                   
2022-02-19 15:26:26.806 T:10082   ERROR <general>: CFileCache::Open - <http://192.168.178.145:8350/stream/2200/13183260614721610628> failed to open
2022-02-19 15:26:26.807 T:10082   ERROR <general>: CVideoPlayer::OpenInputStream - error opening [http://192.168.178.145:8350/stream/2200/13183260614721610628]
2022-02-19 15:26:26.807 T:10082    INFO <general>: CVideoPlayer::OnExit()
2022-02-19 15:26:26.956 T:9609     INFO <general>: Loading skin file: DialogConfirm.xml, load type: KEEP_IN_MEMORY
2022-02-19 15:26:26.987 T:9609     INFO <general>: CVideoPlayer::CloseFile()
2022-02-19 15:26:26.994 T:9609     INFO <general>: VideoPlayer: waiting for threads to exit
2022-02-19 15:26:26.994 T:9609     INFO <general>: VideoPlayer: finished waiting
2022-02-19 15:26:33.543 T:9618     INFO <general>: CActiveAESink::OpenSink - initialize sink
2022-02-19 15:26:33.544 T:9618     INFO <general>: Trying to open: samplerate: 44100, channelMask: 12, encoding: 4
2022-02-19 15:26:33.566 T:9618     INFO <general>: CAESinkAUDIOTRACK::Initializing with: m_sampleRate: 44100 format: AE_FMT_FLOAT (AE) method: PCM stream-type: PCM-STREAM min_buffer_size: 56720 m_frames: 1772 m_frameSize: 8 channels: 2
2022-02-19 15:26:35.512 T:9609     INFO <general>: Loading skin file: DialogButtonMenu.xml, load type: KEEP_IN_MEMORY

**Comment by andrew-ld** [comment]
@Mystery86HH have you updated python recently?

https://github.com/aio-libs/async-lru/issues/383

it seems to be an async lru problem with python 3.10, you should update the dependency to the last commit.

workaround:

```
pip3 uninstall async-lru
pip3 install git+https://github.com/aio-libs/async-lru@3574af7691371015c47faf77e0abf8c7b06a3cdc
```

**Comment by Mystery86HH** [comment]
My Synology NAS uses Python 2.7.18-1004

**Comment by andrew-ld** [comment]
@Mystery86HH are you using docker?

**Comment by Mystery86HH** [comment]
Yes

**Comment by andrew-ld** [comment]
@Mystery86HH solved with the last commit, if you use the precompiled image you have to wait for github workflow to push the image to dockerhub, if you build it from source just update it.

**Comment by Mystery86HH** [comment]
Great, I use the docker hub image. When you think is the GitHub workflow done? Tomorrow morning?

**Comment by andrew-ld** [comment]
https://github.com/andrew-ld/smart-tv-telegram/runs/5308838711?check_suite_focus=true

**Comment by andrew-ld** [comment]
@Mystery86HH build done for x86_64 and armv8

**Comment by Mystery86HH** [comment]
Thank you, it works great again 😁
