### ISSUE TITLE
Unhealthy container / Startup Loop

### ISSUE THREAD

**Issue by Mystery86HH** [andrew-ld/smart-tv-telegram#42]
Someone an idea why my container don't passes the health check since the last update?

`2023-12-15T14:48:59.068690422Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-15T14:48:59.068718442Z   File "/usr/local/lib/python3.11/site-packages/smart_tv_telegram/mtproto.py", line 63, in <genexpr>
2023-12-15T14:48:59.068750423Z     if not all(x.is_connected.is_set() for x in self._client.media_sessions.values()):
2023-12-15T14:48:59.068777338Z                ^^^^^^^^^^^^^^
2023-12-15T14:48:59.068800004Z AttributeError: 'Session' object has no attribute 'is_connected'
2023-12-15T14:49:31.226975893Z ERROR:aiohttp.server:Error handling request
2023-12-15T14:49:31.227418142Z Traceback (most recent call last):
2023-12-15T14:49:31.227458842Z   File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
2023-12-15T14:49:31.227503025Z     resp = await request_handler(request)
2023-12-15T14:49:31.227538959Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-15T14:49:31.227575558Z   File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 504, in _handle
2023-12-15T14:49:31.227609385Z     resp = await handler(request)
2023-12-15T14:49:31.227635947Z            ^^^^^^^^^^^^^^^^^^^^^^
2023-12-15T14:49:31.227659356Z   File "/usr/local/lib/python3.11/site-packages/smart_tv_telegram/http.py", line 99, in _health_check_handler
2023-12-15T14:49:31.227695903Z     await self._mtproto.health_check()
2023-12-15T14:49:31.227723063Z   File "/usr/local/lib/python3.11/site-packages/smart_tv_telegram/mtproto.py", line 63, in health_check
2023-12-15T14:49:31.227754229Z     if not all(x.is_connected.is_set() for x in self._client.media_sessions.values()):
2023-12-15T14:49:31.227786516Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-15T14:49:31.227813540Z   File "/usr/local/lib/python3.11/site-packages/smart_tv_telegram/mtproto.py", line 63, in <genexpr>
2023-12-15T14:49:31.227845481Z     if not all(x.is_connected.is_set() for x in self._client.media_sessions.values()):
2023-12-15T14:49:31.227873528Z                ^^^^^^^^^^^^^^`

**Comment by Mystery86HH** [comment]
I have to update that issue. Streaming on tv works good, it's only the container health check that says unhealthy...

**Comment by andrew-ld** [comment]
Looks like a breaking changes of the latest version of pyrogram, I need to update the heath check part

**Comment by Mystery86HH** [comment]
Thank you very much for developing my most loved TG-Bot ♥️

**Comment by andrew-ld** [comment]
fixed by @davtur19

**Comment by andrew-ld** [comment]
released 1.3.8
