### ISSUE TITLE
No device selection

### ISSUE THREAD

**Issue by Mystery86HH** [andrew-ld/smart-tv-telegram#44]
Hello, I have a problem. If I send a video to the bot, the bot answers with "select a Device" but there are no devices to select. If I write the Device name manually, the video starts on that Device. Only the selection is gone since a while. 

Maybe the log can help: 
`2024-05-22T07:58:43.140401793Z ERROR:aiohttp.server:Error handling request
2024-05-22T07:58:43.140944594Z Traceback (most recent call last):
2024-05-22T07:58:43.140983823Z   File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
2024-05-22T07:58:43.141028033Z     resp = await request_handler(request)
2024-05-22T07:58:43.141057184Z   File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
2024-05-22T07:58:43.141103118Z     resp = await handler(request)
2024-05-22T07:58:43.141130795Z   File "/usr/local/lib/python3.10/site-packages/smart_tv_telegram/http.py", line 254, in _stream_handler
2024-05-22T07:58:43.141164693Z     await stream.write(block)
2024-05-22T07:58:43.141191733Z   File "/usr/local/lib/python3.10/site-packages/aiohttp/web_response.py", line 514, in write
2024-05-22T07:58:43.141221595Z     await self._payload_writer.write(data)
2024-05-22T07:58:43.141250742Z   File "/usr/local/lib/python3.10/site-packages/aiohttp/http_writer.py", line 119, in write
2024-05-22T07:58:43.141281499Z     await self.drain()
2024-05-22T07:58:43.141308766Z   File "/usr/local/lib/python3.10/site-packages/aiohttp/http_writer.py", line 171, in drain
2024-05-22T07:58:43.141337242Z     await self._protocol._drain_helper()
2024-05-22T07:58:43.141362139Z   File "/usr/local/lib/python3.10/site-packages/aiohttp/base_protocol.py", line 90, in _drain_helper
2024-05-22T07:58:43.141434448Z     await asyncio.shield(waiter)
2024-05-22T07:58:43.141465108Z   File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 862, in _read_ready__data_received
2024-05-22T07:58:43.141497177Z     data = self._sock.recv(self.max_size)
2024-05-22T07:58:43.141522953Z ConnectionResetError: [Errno 104] Connection reset by peer
2024-05-22T07:58:48.957245663Z ERROR:aiohttp.server:Error handling request
2024-05-22T07:58:48.957708244Z Traceback (most recent call last):
2024-05-22T07:58:48.957750178Z   File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
2024-05-22T07:58:48.957796130Z     resp = await request_handler(request)
2024-05-22T07:58:48.957825777Z   File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
2024-05-22T07:58:48.957858421Z     resp = await handler(request)
2024-05-22T07:58:48.957910954Z   File "/usr/local/lib/python3.10/site-packages/smart_tv_telegram/http.py", line 254, in _stream_handler
2024-05-22T07:58:48.957945758Z     await stream.write(block)
2024-05-22T07:58:48.957972569Z   File "/usr/local/lib/python3.10/site-packages/aiohttp/web_response.py", line 514, in write
2024-05-22T07:58:48.958005139Z     await self._payload_writer.write(data)
2024-05-22T07:58:48.958032105Z   File "/usr/local/lib/python3.10/site-packages/aiohttp/http_writer.py", line 119, in write
2024-05-22T07:58:48.958117828Z     await self.drain()
2024-05-22T07:58:48.958144464Z   File "/usr/local/lib/python3.10/site-packages/aiohttp/http_writer.py", line 171, in drain
2024-05-22T07:58:48.958173747Z     await self._protocol._drain_helper()
2024-05-22T07:58:48.958199047Z   File "/usr/local/lib/python3.10/site-packages/aiohttp/base_protocol.py", line 90, in _drain_helper
2024-05-22T07:58:48.958230024Z     await asyncio.shield(waiter)
2024-05-22T07:58:48.958256447Z   File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 862, in _read_ready__data_received
2024-05-22T07:58:48.958291280Z     data = self._sock.recv(self.max_size)
2024-05-22T07:58:48.958317272Z ConnectionResetError: [Errno 104] Connection reset by peer
`

Maybe anyone can help?

**Comment by andrew-ld** [comment]
i think that is a bug of the telegram client that you use, maybe try with another telegram client

**Comment by Mystery86HH** [comment]
You're right. It seems the last update on plus messenger has a bug. The origin telegram client show me the devices... :(

**Comment by Mystery86HH** [comment]
Ok, now it works on plus messenger again, after I used the telegram client..
